name: Docker build & push

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v3

    - name: Step 2 - Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Step 3 - Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Step 4 - Test with pytest
      run: |
        pytest

    - name: Step 5 - Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          xfneo/container-reload
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.0.') }}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

    - name: Step 6 - Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Step 7 - Docker build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
